version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "3009:3000"
      - "9009:9000"
    expose:
      - 3000
      - 9000
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
        - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    env_file: .env
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports: 
      - 33068:3306
    expose:
      - 3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network
  sso-nginx:
    image: nginx:stable-alpine
    env_file: .env
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - app
    ports:
      - 8092:80
      - 8492:443
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./:/var/www/html/
    networks:
      app-network:

networks:
  mysql_data:
     driver: local
  app-network:
    driver: bridge
